package ru.gubatenko.domain

const val DAO_IDEA_SQLITE = "DATABASE_SOURCE_SQLITE"

const val MAPPER_DOMAIN_TO_STORED_SQLITE_ACTION = "MAPPER_DOMAIN_TO_STORED_SQLITE_ACTION"
const val MAPPER_DOMAIN_TO_DTO_ACTION = "MAPPER_DOMAIN_TO_DTO_ACTION"
const val MAPPER_STORED_TO_DOMAIN_ACTION = "MAPPER_STORED_TO_DOMAIN_ACTION"
const val MAPPER_DTO_TO_DOMAIN_ACTION = "MAPPER_DTO_TO_DOMAIN_ACTION"

const val CUSTOM_DATA_STORE = "CUSTOM_DATA_STORE"
const val SIMPLE_VALUE_DATA_STORE = "SIMPLE_VALUE_DATA_STORE"
