package ru.gubatenko.domain

const val MAPPER_DOMAIN_TO_STORED_ACTION = "MAPPER_DOMAIN_TO_STORED_ACTION"
const val MAPPER_DOMAIN_TO_DTO_ACTION = "MAPPER_DOMAIN_TO_DTO_ACTION"
const val MAPPER_STORED_TO_DOMAIN_ACTION = "MAPPER_STORED_TO_DOMAIN_ACTION"
const val MAPPER_DTO_TO_DOMAIN_ACTION = "MAPPER_DTO_TO_DOMAIN_ACTION"