name: Android CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          
      - name: Run Unit tests
        run: bash ./gradlew test --stacktrace
   
  apk-build:
    name: Generate APK
    needs: unit-test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
            
      - name: Assemble app debug APK
        run: bash ./gradlew assemble
        
      - name: Upload app APK
        uses: actions/upload-artifact@v1
        with:
          name: app-development-release
          path: app/build/outputs/apk/development/release/app-development-release.apk
          
      - name: Assemble Android Instrumentation Tests
        run: bash ./gradlew assembleAndroidTest -DtestBuildType=release
        
      - name: Upload Android Test APK
        uses: actions/upload-artifact@v1
        with:
          name: app-development-release-androidTest
          path: app/build/outputs/apk/androidTest/development/release/app-development-release-androidTest.apk
          
      - uses: actions/checkout@v1
  firebase-test-lab:
      name: Firebase Test Lab
      needs: apk-build
      runs-on: ubuntu-18.04

      steps:
        - uses: actions/checkout@v1
        
        - name: Download app APK
          uses: actions/download-artifact@v1
          with:
            name: app-development-release

        - name: Download Android test APK
          uses: actions/download-artifact@v1
          with:
            name: app-development-release-androidTest

        - name: Login to Google Cloud
          uses: google-github-actions/setup-gcloud@master
          with: 
            version: '270.0.0' 
            service_account_key: ${{secrets.SERVICE_ACCOUNT}}

        - name: Set current project
          run: gcloud config set project ${{secrets.FIREBASE_PROMISES_APP_ID}}
          
        - name: Run Instrumentation Tests in Firebase Test Lab
          run: gcloud firebase test android run --type instrumentation --app app-development-release/app-development-release.apk --test app-development-release-androidTest/app-development-release-androidTest.apk --device model=Pixel2,version=28,locale=en,orientation=portrait

        - name: Run Robo Tests in Firebase Test Lab
          run: gcloud firebase test android run --type robo --app app-development-release/app-development-release.apk --device model=Pixel2,version=28,locale=en,orientation=portrait

  firebase-app-distribution:
      name: Firebase App Distribution
      needs: firebase-test-lab
      runs-on: ubuntu-18.04

      steps:
        - uses: actions/checkout@v1

        - name: Download app APK
          uses: actions/download-artifact@v1
          with:
            name: app-development-release

        - name: Firebase App Distribution
          uses: wzieba/Firebase-Distribution-Github-Action@v1
          with:
            appId: ${{secrets.FIREBASE_APP_ID}}
            token: ${{secrets.FIREBASE_TOKEN}}
            groups: testers
            file: app-development-release/app-development-release.apk            
