name: Android CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          
      - name: Run Unit tests
        run: bash ./gradlew test --stacktrace
        
      - name: Assemble app debug APK
        run: bash ./gradlew assembleDebug
        
      - name: Upload app APK
        uses: actions/upload-artifact@v1
        with:
          name: app-development-debug
          path: app/build/outputs/apk/development/debug/app-development-debug.apk
          
      - name: Assemble Android Instrumentation Tests
        run: bash ./gradlew assembleAndroidTest
        
      - name: Upload Android Test APK
        uses: actions/upload-artifact@v1
        with:
          name: app-development-debug-androidTest
          path: app/build/outputs/apk/androidTest/development/debug/app-development-debug-androidTest.apk
        
      - name: Download app APK
        uses: actions/download-artifact@v1
        with:
          name: app-development-debug
          
      - name: Download Android test APK
        uses: actions/download-artifact@v1
        with:
          name: app-development-debug-androidTest
          
#       - name: Login to Google Cloud
#         uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
#         with: 
#           version: '270.0.0' 
#           service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
          
#       - name: Set current project
#         run: gcloud config set project ${{ secrets.FIREBASE_APP_ID }}
        
#       - name: Run Instrumentation Tests in Firebase Test Lab
#         run: gcloud firebase test android run --type instrumentation --app app-debug/app-debug.apk --test app-debug-androidTest/app-debug-androidTest.apk --device model=Pixel2,version=28,locale=en,orientation=portrait

#     steps:
#     - uses: actions/checkout@v2
#     - name: set up JDK 11
#       uses: actions/setup-java@v2
#       with:
#         java-version: '11'
#         distribution: 'adopt'
#         cache: gradle
        
#     - name: Unit tests
#       run: ./gradlew test
#     - name: Build release 
#       run: ./gradlew assembleRelease
#     - name: Run tests on Firebase Test Lab
#       uses: asadmansr/Firebase-Test-Lab-Action@v1.0
#       with:
#           arg-spec: 'tests.yml:android-pixel-4'
#       env:
#           SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
#     - name: Firebase App Distribution
#       uses: wzieba/Firebase-Distribution-Github-Action@v1
#       with:
#         appId: ${{secrets.FIREBASE_APP_ID}}
#         token: ${{secrets.FIREBASE_TOKEN}}
#         groups: testers
#         file: app/build/outputs/apk/development/release/app-development-release.apk
